import { createClient } from '@supabase/supabase-js';

// Ganti nilai di bawah ini dengan URL dan Anon Key dari Dashboard Supabase Anda
// Simpan nilai ini di file .env untuk keamanan saat deploy (VITE_SUPABASE_URL & VITE_SUPABASE_ANON_KEY)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'YOUR_SUPABASE_URL';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * STRUKTUR TABEL SUPABASE (SQL untuk Query Console):
 * 
 * -- Tabel Laporan
 * CREATE TABLE reports (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   created_at TIMESTAMPTZ DEFAULT NOW(),
 *   reporter_name TEXT NOT NULL,
 *   division TEXT NOT NULL,
 *   category TEXT NOT NULL,
 *   description TEXT NOT NULL,
 *   drive_link TEXT,
 *   status TEXT DEFAULT 'Menunggu',
 *   admin_note TEXT,
 *   resolution_link TEXT,
 *   accepted_at TIMESTAMPTZ,
 *   completed_at TIMESTAMPTZ,
 *   complaint_number TEXT        -- Format: BM-YYYYMMDD-XXXX (nullable, hanya laporan baru)
 * );
 * 
 * -- ALTER TABLE jika sudah ada (Jalankan ini di SQL Editor):
 * ALTER TABLE reports 
 * ADD COLUMN IF NOT EXISTS category TEXT,
 * ADD COLUMN IF NOT EXISTS admin_note TEXT,
 * ADD COLUMN IF NOT EXISTS resolution_link TEXT,
 * ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ,
 * ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
 * 
 * -- Pastikan default status adalah Menunggu
 * ALTER TABLE reports ALTER COLUMN status SET DEFAULT 'Menunggu';
 * 
 * -- Tabel User/PIN
 * CREATE TABLE profiles (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   pin TEXT NOT NULL,
 *   role TEXT NOT NULL CHECK (role IN ('admin', 'reporter'))
 * );
 */
